String.toLocaleString({

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'oakton',
    '%4'                    : 'illinois state',
    '%8'                    : 'university of alabama',
    '%16'                   : 'penn state',
    '%32'                   : 'UIC',
    '%64'                   : 'NYU',
    '%128'                  : 'university of michigan',
    '%256'                  : 'ucla',
    '%512'                  : 'duke',
    '%1024'                 : 'columbia',
    '%2048'                 : 'yale',
    '%4096'                 : 'harvard',
    '%8192'                 : 'stanford',
    '%p0'                   : 'oakton',
    '%p4'                   : 'illinois state',
    '%p8'                   : 'university of alabama',
    '%p16'                  : 'penn state',
    '%p32'                  : 'UIC',
    '%p64'                  : 'NYU',
    '%p128'                 : 'university of michigan',
    '%p256'                 : 'ucla',
    '%p512'                 : 'duke',
    '%p1024'                : 'columbia',
    '%p2048'                : 'yale',
    '%p4096'                : 'harvard',
    '%p8192'                : 'stanford'
  }

});
